# Generated by Django 4.2.6 on 2023-11-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0002_user_avatar_user_phone_alter_criteria_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.RemoveField(
            model_name='memberofthesisdefensecommittee',
            name='Committee',
        ),
        migrations.RemoveField(
            model_name='memberofthesisdefensecommittee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='memberofthesisdefensecommittee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='memberofcommittee',
        ),
        migrations.RemoveField(
            model_name='score',
            name='scoreofstudent',
        ),
        migrations.DeleteModel(
            name='StatusThesis',
        ),
        migrations.RemoveField(
            model_name='thesisexaminationcommittee',
            name='Committee',
        ),
        migrations.RemoveField(
            model_name='thesisexaminationcommittee',
            name='thesis',
        ),
        migrations.RemoveField(
            model_name='thesisstudent',
            name='thesis',
        ),
        migrations.RemoveField(
            model_name='thesisstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thesissupervisor',
            name='thesis',
        ),
        migrations.RemoveField(
            model_name='thesissupervisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.DeleteModel(
            name='MemberOfThesisDefenseCommittee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
        migrations.DeleteModel(
            name='ThesisDefenseCommittee',
        ),
        migrations.DeleteModel(
            name='ThesisExaminationCommittee',
        ),
        migrations.DeleteModel(
            name='ThesisStudent',
        ),
        migrations.DeleteModel(
            name='ThesisSupervisor',
        ),
    ]
