# Generated by Django 4.2.6 on 2023-11-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='thesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ThesisManagement.thesis'),
        ),
    ]
