# Generated by Django 4.2.7 on 2023-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0008_alter_user_avatar_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
