# Generated by Django 4.2.7 on 2023-12-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0014_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisexaminationcommittee',
            name='Committee',
        ),
        migrations.RemoveField(
            model_name='thesisexaminationcommittee',
            name='thesis',
        ),
        migrations.AddField(
            model_name='thesisdefensecommittee',
            name='thesis',
            field=models.ManyToManyField(to='ThesisManagement.thesis'),
        ),
    ]
