# Generated by Django 4.2.7 on 2023-12-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0015_remove_thesisexaminationcommittee_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='ThesisManagement.statusthesis'),
            preserve_default=False,
        ),
    ]
