# Generated by Django 4.2.7 on 2023-12-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='memberofcommittee',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='scoreofstudent',
            new_name='student',
        ),
    ]
