# Generated by Django 4.2.7 on 2023-12-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0021_score_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ThesisManagement.memberofthesisdefensecommittee'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ThesisManagement.thesisstudent'),
        ),
    ]
