# Generated by Django 4.2.7 on 2023-12-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0024_majors_alter_user_role_thesis_major_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
