# Generated by Django 4.2.7 on 2024-01-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0027_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesissupervisor',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác'), ('secret', 'Bí Mật')], max_length=255, null=True),
        ),
    ]
