# Generated by Django 4.2.7 on 2024-01-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0030_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='status',
        ),
        migrations.AddField(
            model_name='thesisdefensecommittee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ThesisManagement.statusthesis'),
        ),
    ]
