# Generated by Django 4.2.7 on 2024-01-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0031_remove_thesis_status_thesisdefensecommittee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
