# Generated by Django 4.2.7 on 2024-01-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisManagement', '0034_remove_message_room_message_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
    ]
